杂记/jd_shujufenxi/jd/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2019/1/5  10:15
# @Author  : zhangxinxin
# @Email   : 778786617@qq.com
# @Software: PyCharm
from django.urls import path
from . import views


app_name = 'jd'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<str:s_id>', views.detail, name='detail'),
    path('show_svg/<str:s_id>', views.show_svg, name='show_svg')
]

杂记/jd_shujufenxi/jd_shujufenxi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jd/', include('jd.urls'))
]

杂记/jd_shujufenxi/jd/models.py
from django.db import models


class Comment(models.Model):
    id = models.IntegerField(max_length=10, auto_created=True, primary_key=True)
    p_id = models.CharField(max_length=20)
    user_id = models.IntegerField(max_length=15)
    p_content = models.TextField('评论内容', default="")
    p_name = models.CharField(max_length=80)
    p_color = models.CharField(max_length=20)
    p_size = models.CharField(max_length=20)
    p_zan = models.IntegerField(max_length=6)
    p_pinglun = models.IntegerField(max_length=6)
    p_type = models.IntegerField(max_length=5)
    user_vip = models.CharField(max_length=10)
    p_creation_time = models.CharField(max_length=15)

    # def __str__(self):
        # return self.p_content


class Commodity(models.Model):
    s_id = models.CharField(max_length=20, primary_key=True)
    s_name = models.TextField()
    s_price = models.FloatField(max_length=10)

    def __str__(self):
        return self.s_name

杂记/jd_shujufenxi/jd/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Comment, Commodity
from .get_jd_comments import JdComment
from .image_jd_comments import JdShow


def index(request):
    commodity_list = Commodity.objects.filter()
    print(commodity_list)
    return render(request, 'html/index.html', {'commodity_list': commodity_list})


def detail(request, s_id):
    # s_id = request.GET.get("id")
    print("sndasndas,", s_id)
    content_list = Comment.objects.filter(p_id=s_id)
    print(content_list)
    if not content_list:
        print('数据库无此商品信息，信息采集中，请稍后')
        s_id = int(s_id)
        JdComment().run(s_id=s_id)
        content_list = Comment.objects.filter(p_id=s_id)
    return render(request, 'html/detail.html', {'content_list': content_list, 'h1': s_id})


def show_svg(request, s_id):
    print("sndasndas,", s_id)
    JdShow().run(s_id)
    with open('JD数据可视化(条形图).svg', 'r', encoding='UTF-8') as f:
        a = f.read()

    return HttpResponse(a)

杂记/jd_shujufenxi/templates/html/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <!--  引用bootstrap css js, jquery-->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <script src="https://cdn.bootcss.com/twitter-bootstrap/4.1.3/js/bootstrap.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

杂记/jd_shujufenxi/templates/html/detail.html
{% extends 'html/base.html' %}
{% block title %}{{ s_id }}{% endblock %}
{% block content %}
  <h1>{{ h1 }}的所有手机评论</h1>
  <h3><a href="{% url 'jd:show_svg' h1 %}" methods="GET">看着太麻烦？来点我</a></h3>
  <table style="border: 1px black solid">
  <tr style="border: 1px black solid">
  <td>用户id</td>
  <td>手机名</td>
  <td>手机颜色</td>
  <td>手机型号</td>
  <td>点赞数</td>
  <td>评论数</td>
  <td>用户vip等级</td>
  <td>评论发表时间</td>
  <td>评论内容</td>
  </tr>
  {% for con in content_list %}
    <tr style="border: 1px black solid">
    <td>{{ con.user_id }}</td>
    <td>{{ con.p_name }}</td>
    <td>{{ con.p_color }}</td>
    <td>{{ con.p_size }}</td>
    <td>{{ con.p_zan }}</td>
    <td>{{ con.p_pinglun }}</td>
    <td>{{ con.user_vip }}</td>
    <td>{{ con.p_creation_time }}</td>
    <td>{{ con.p_content }}</td>
    </tr>
  {% endfor %}
</table>

{% endblock %}

杂记/jd_shujufenxi/templates/html/index.html
{% extends 'html/base.html' %}
{% block title %}商品列表页{% endblock %}
{% block content %}
  <h1 style="text-align: center">商品列表页</h1>

  <table style="border: 1px black solid">
    <tr style="border: 1px black solid">
      <td>商品id</td>
      <td>商品名</td>
      <td>商品价格</td>
    </tr>
  {% for commodity in commodity_list %}
    <tr style="border: 1px black solid">
      <td><a href="{% url 'jd:detail' commodity.s_id %}" methods="GET">{{ commodity.s_id }}</a></td>
      <td>{{ commodity.s_name }}</td>
      <td>{{ commodity.s_price }}</td>
    </tr>
  {% endfor %}
  </table>

{% endblock %}

杂记/jd_shujufenxi/templates/html/showsvg.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>条形图</title>
</head>
<body>
<h1>此处应有一个条形图</h1>
</body>
</html>